# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

name = "jeni-extension-app"
client_id = "79d015ec0ac8ec3596bea94928934b31"
application_url = "https://shopify.dev/apps/default-app-home"
embedded = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = ""

[auth]
redirect_urls = [ "https://shopify.dev/apps/default-app-home/api/auth" ]

[webhooks]
api_version = "2024-07"

[pos]
embedded = false

[build]
dev_store_url = "jeni-dev-test.myshopify.com"
